name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Update repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.DEPLOY_FTP_HOST }}
        username: ${{ secrets.DEPLOY_FTP_USER }}
        password: ${{ secrets.DEPLOY_FTP_PASS }}
        dry-run: true
        exclude: |
          .gitignore
          .github/**
          **/.git*
          **/.git*/**