name: Deploy

on:

  push:
    tags:
      - '*'

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy
        uses: pressidium/lftp-mirror-action@v1
        with:

          # SFTP credentials
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}

          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          forceSSL: false
          verifyCertificate: false
          restoreMTime: false # Ignore filetime, takes too long.

          # Mirror command options
          localDir: './'
          remoteDir: './'
          reverse: true
          options: >-
            --verbose
            --delete
            --exclude-glob *
            --include-glob plugins/**
            --include-glob mu-plugins/**
            --include-glob themes/**
            --include-glob db.php
            --ignore-time
