name: Deploy to aubreypwd.com

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy wp-content/*
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.DEPLOY_FTP_HOST }}
          port: ${{ secrets.DEPLOY_FTP_PORT }}
          user: ${{ secrets.DEPLOY_FTP_USER }}
          pass: ${{ secrets.DEPLOY_FTP_PASS }}
          localDir: './wp-content'
          remoteDir: '.'
          reverse: true
          restoreMTime: false
          settings: 'ftp:auto-confirm=yes'
          options: >-
            --delete
            --ignore-time
            --include-glob plugins/**
            --include-glob mu-plugins/**
            --include-glob themes/**
            --include-glob db.php
            --exclude-glob *